Update jar-regression.yml

diff --git a/.github/workflows/jar-regression.yml b/.github/workflows/jar-regression.yml
--- a/.github/workflows/jar-regression.yml
+++ b/.github/workflows/jar-regression.yml
@@ -531,33 +531,45 @@ jobs:
         env:
           BRANCH: ${{ needs.download_configs.outputs.branch }}
         run: |
+          cd .ci-temp/contribution/checkstyle-tester
+          bash
           REF="forked/$BRANCH"
-          REPO="$GITHUB_WORKSPACE"
+          REPO="${{ github.workspace }}/.ci-temp/checkstyle"
           BASE_BRANCH="upstream/master"
-          CONFIG_FILE="$GITHUB_WORKSPACE/.ci-temp/diff_config.xml"
-          PROJECTS_FILE="$GITHUB_WORKSPACE/.ci-temp/project.properties"
-      
+          export MAVEN_OPTS="-Xmx5g"
+          
+          DIFF_TOOL_JAR="${{ github.workspace }}/diff-java-tool-all.jar"
+          
           echo "Current directory: $(pwd)"
           echo "BRANCH: $BRANCH"
           echo "REF: $REF"
           echo "REPO: $REPO"
           echo "BASE_BRANCH: $BASE_BRANCH"
-          echo "CONFIG_FILE: $CONFIG_FILE"
-          echo "PROJECTS_FILE: $PROJECTS_FILE"
-      
-          java -jar diff-java-tool-all.jar \
-            --localGitRepo "$REPO" \
-            --baseBranch "$BASE_BRANCH" \
-            --patchBranch "$REF" \
-            --config "$CONFIG_FILE" \
-            --listOfProjects "$PROJECTS_FILE" \
-            --allowExcludes
+          echo "DIFF_TOOL_JAR: $DIFF_TOOL_JAR"
+          
+          if [ -f new_module_config.xml ]; then
+            java -jar $DIFF_TOOL_JAR -r "$REPO" -p "$REF" -pc new_module_config.xml -m single \
+              -l project.properties -xm "-Dcheckstyle.failsOnError=false" \
+              --allowExcludes
+          elif [ -f patch_config.xml ]; then
+            java -jar $DIFF_TOOL_JAR -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -bc diff_config.xml \
+              -pc patch_config.xml -l project.properties -xm "-Dcheckstyle.failsOnError=false" \
+              --allowExcludes
+          else
+            java -jar $DIFF_TOOL_JAR -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -c diff_config.xml \
+              -l project.properties -xm "-Dcheckstyle.failsOnError=false" \
+              --allowExcludes
+          fi
+          
+          if [ $? -ne 0 ]; then
+            echo "Error occurred during report generation"
+            ./.ci/append-to-github-output.sh "error" "true"
+            exit 1
+          fi
       
           # Debug output
           echo "Current directory structure:"
           find . -type d
-          echo "Contents of target directory:"
-          ls -la target/
           echo "Contents of reports directory:"
           ls -la reports/
           echo "Contents of tmp_reports directory:"
