Update regression-report.yml

diff --git a/.github/workflows/regression-report.yml b/.github/workflows/regression-report.yml
--- a/.github/workflows/regression-report.yml
+++ b/.github/workflows/regression-report.yml
@@ -13,11 +13,11 @@
 #####################################################################################
 name: regression-report
 env:
-  AWS_REGION: us-east-2
-  AWS_BUCKET_NAME: "checkstyle-diff-reports"
+  AWS_REGION: ap-south-1
+  AWS_BUCKET_NAME: "chesktyler-reports"
   USER_LOGIN: ${{ github.event.issue.user.login }}
   # yamllint disable-line rule:line-length
-  DEFAULT_PROJECTS_LINK: "https://raw.githubusercontent.com/checkstyle/test-configs/main/extractor/src/main/resources/list-of-projects.properties"
+  DEFAULT_PROJECTS_LINK: "https://raw.githubusercontent.com/checkstyle/test-configs/main/extractor/src/main/resources/projects.yml"
   BASE_TEST_CONFIGS_URL: "https://raw.githubusercontent.com/checkstyle/test-configs/main"
   EXTRACTOR_VERSION: 2024-08-27
   DIFF_TOOL_VERSION: "1.0-SNAPSHOT-all"
@@ -118,7 +118,6 @@ jobs:
           git checkout -b ${{ steps.get_pr_details.outputs.branch }} \
                forked/${{ steps.get_pr_details.outputs.branch }}
 
-
       - name: Save cache
         uses: actions/cache/save@v4
         with:
@@ -201,7 +200,7 @@ jobs:
           BASE_URL="${{ env.BASE_TEST_CONFIGS_URL }}"
           CONFIG_BUNDLE="${{ needs.parse_comment.outputs.config_bundle }}"
           CONFIG_LINK="$BASE_URL/$CONFIG_BUNDLE/config.xml"
-          PROJECTS_LINK="$BASE_URL/$CONFIG_BUNDLE/list-of-projects.properties"
+          PROJECTS_LINK="$BASE_URL/$CONFIG_BUNDLE/list-of-projects.yml"
           ./.ci/append-to-github-output.sh "config_link" "$CONFIG_LINK"
           ./.ci/append-to-github-output.sh "projects_link" "$PROJECTS_LINK"
 
@@ -275,8 +274,8 @@ jobs:
           CONFIG_FILE_NAME=$(basename "$FOUND_FILE" .java)_config.xml
           CONFIG_FILE_PATH="$OUTPUT_DIR/$CONFIG_FILE_NAME"
 
-          # Generate a name for the projects file
-          PROJECT_FILE_PATH="$OUTPUT_DIR/projects.properties"
+          # Generate a name for the projects YAML file
+          PROJECT_FILE_PATH="$OUTPUT_DIR/projects.yml"
 
           # Run the extractor
           java -jar extractor-all-${{env.EXTRACTOR_VERSION}}.jar \
@@ -292,6 +291,9 @@ jobs:
           # Print the contents of the files to the logs
           echo "Contents of CONFIG_FILE_PATH:"
           cat "$CONFIG_FILE_PATH"
+
+          echo "Contents of PROJECT_FILE_PATH:"
+          cat "$PROJECT_FILE_PATH"
 
       - name: Cache Generated Config and Project Files
         uses: actions/cache@v4
@@ -339,7 +341,7 @@ jobs:
       - name: Parsing content of PR description
         id: parse_description
         run: |
-          ./.ci/diff-report.sh parse-pr-description-text
+          ./.ci/diff-report-new.sh parse-pr-description-text
 
   download_configs:
     needs: [
@@ -366,7 +368,8 @@ jobs:
       - name: Restore cache
         uses: actions/cache/restore@v4
         with:
-          path: .
+          path: |
+            .
           key: ${{ env.CACHE_KEY }}
           fail-on-cache-miss: true
 
@@ -387,7 +390,7 @@ jobs:
           echo "Config link: $DIFF_CONFIG_LINK"
           echo "Projects link: $DIFF_PROJECTS_LINK"
           cp "$DIFF_CONFIG_LINK" .ci-temp/diff_config.xml
-          cp "$DIFF_PROJECTS_LINK" .ci-temp/project.properties
+          cp "$DIFF_PROJECTS_LINK" .ci-temp/projects.yml
 
       - name: Download URL-based Config and Project File
         id: download_files
@@ -414,17 +417,22 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mkdir -p .ci-temp
-          if ! ./.ci/diff-report.sh download-files; then
+          ls -la .ci 
+          git log -1
+          if ! ./.ci/diff-report-new.sh download-files; then
             ./.ci/append-to-github-output.sh "failed" "true"
             exit 1
           fi
+      
+      - name: List .ci-temp directory
+        run: ls -la .ci-temp
 
       - name: Cache config files
         uses: actions/cache@v4
         with:
           path: |
             .ci-temp/*.xml
-            .ci-temp/project.properties
+            .ci-temp/projects.yml
           key: ${{ env.CACHE_KEY }}-config-files
 
   make_report:
@@ -446,7 +454,7 @@ jobs:
         with:
           path: |
             .ci-temp/*.xml
-            .ci-temp/project.properties
+            .ci-temp/projects.yml
           key: ${{ env.CACHE_KEY }}-config-files
 
       - name: Restore local maven cache
@@ -496,16 +504,21 @@ jobs:
           fi
           echo "-------------------------"
 
-      - name: Print project.properties
+      - name: Print projects file
         run: |
-          echo "Contents of project.properties:"
-          echo "-------------------------------"
-          if [ -f .ci-temp/project.properties ]; then
-            cat .ci-temp/project.properties
+          if [ -f .ci-temp/projects.yml ]; then
+            echo "Contents of projects.yml:"
+            echo "-------------------------------"
+            cat .ci-temp/projects.yml
+            echo "-------------------------------"
+          elif [ -f .ci-temp/projects.properties ]; then
+            echo "Contents of projects.properties:"
+            echo "-------------------------------"
+            cat .ci-temp/projects.properties
+            echo "-------------------------------"
           else
-            echo "project.properties not found"
+            echo "No projects file found"
           fi
-          echo "-------------------------------"
 
       - name: Print patch_config.xml
         run: |
@@ -532,48 +545,55 @@ jobs:
       - name: Generate report
         run: |
           cd .ci-temp
-          bash
           PR_BRANCH="${{ needs.checkout_and_cache.outputs.pr_branch }}"
           REPO="${{ github.workspace }}/.ci-temp/checkstyle"
           BASE_BRANCH="upstream/master"
           export MAVEN_OPTS="-Xmx5g"
-
+      
           # Paths to config files
           DIFF_CONFIG="${{ github.workspace }}/.ci-temp/diff_config.xml"
           PATCH_CONFIG="${{ github.workspace }}/.ci-temp/patch_config.xml"
           NEW_MODULE_CONFIG="${{ github.workspace }}/.ci-temp/new_module_config.xml"
-          PROJECT_PROPERTIES="${{ github.workspace }}/.ci-temp/project.properties"
-
+      
+          # Determine the projects file path
+          if [ -f "${{ github.workspace }}/.ci-temp/projects.yml" ]; then
+            PROJECTS_FILE="${{ github.workspace }}/.ci-temp/projects.yml"
+          elif [ -f "${{ github.workspace }}/.ci-temp/projects.properties" ]; then
+            PROJECTS_FILE="${{ github.workspace }}/.ci-temp/projects.properties"
+          else
+            echo "Error: Projects file not found."
+            exit 1
+          fi
+      
           # Paths to the JAR files
           DIFFTOOL_JAR="diff-java-tool-${{ env.DIFF_TOOL_VERSION }}.jar"
-          PATCH_DIFF_TOOL_JAR="patch-diff-report-tool-\
-          ${{ env.PATCH_DIFF_TOOL_VERSION }}-jar-with-dependencies.jar"
-
+          PATCH_DIFF_TOOL_JAR="patch-diff-report-tool-${{ env.PATCH_DIFF_TOOL_VERSION }}-jar-with-dependencies.jar"
+      
           # Run DiffTool with appropriate arguments
           if [ -f "$NEW_MODULE_CONFIG" ]; then
             echo "Generating report for new module"
             java -jar "$DIFFTOOL_JAR" -r "$REPO" -p "$PR_BRANCH" -pc "$NEW_MODULE_CONFIG" \
-              -m single -l "$PROJECT_PROPERTIES" -xm "-Dcheckstyle.failsOnError=false" \
+              -m single -l "$PROJECTS_FILE" -xm "-Dcheckstyle.failsOnError=false" \
               --allowExcludes --diffToolJarPath "$PATCH_DIFF_TOOL_JAR"
           elif [ -f "$PATCH_CONFIG" ]; then
             echo "Generating report with patch config"
             java -jar "$DIFFTOOL_JAR" -r "$REPO" -b "$BASE_BRANCH" \
               -p "$PR_BRANCH" -bc "$DIFF_CONFIG" \
-              -pc "$PATCH_CONFIG" -l "$PROJECT_PROPERTIES" -xm "-Dcheckstyle.failsOnError=false" \
+              -pc "$PATCH_CONFIG" -l "$PROJECTS_FILE" -xm "-Dcheckstyle.failsOnError=false" \
               --allowExcludes --diffToolJarPath "$PATCH_DIFF_TOOL_JAR"
           else
             echo "Generating standard diff report"
             java -jar "$DIFFTOOL_JAR" -r "$REPO" -b "$BASE_BRANCH" -p "$PR_BRANCH" \
-              -c "$DIFF_CONFIG" -l "$PROJECT_PROPERTIES" -xm "-Dcheckstyle.failsOnError=false" \
+              -c "$DIFF_CONFIG" -l "$PROJECTS_FILE" -xm "-Dcheckstyle.failsOnError=false" \
               --allowExcludes --diffToolJarPath "$PATCH_DIFF_TOOL_JAR"
           fi
+
 
       - name: Copy Report to AWS S3 Bucket
         env:
           LABEL: ${{ needs.download_configs.outputs.report_label }}
           COMMIT_SHA: ${{ needs.checkout_and_cache.outputs.commit_sha }}
         run: |
-          bash
           TIME=$(date +%Y%H%M%S)
           FOLDER="${COMMIT_SHA}_$TIME"
           DIFF="./.ci-temp/reports/diff"
@@ -615,9 +635,9 @@ jobs:
       make_report ]
     if: always()
       && (needs.make_report.result == 'failure'
-          || needs.make_report.outputs.message != ''
-          || needs.download_configs.result == 'failure'
-          || needs.handle_generated_config_bundle.result == 'failure')
+      || needs.make_report.outputs.message != ''
+      || needs.download_configs.result == 'failure'
+      || needs.handle_generated_config_bundle.result == 'failure')
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
