Update regression-report.yml

diff --git a/.github/workflows/regression-report.yml b/.github/workflows/regression-report.yml
--- a/.github/workflows/regression-report.yml
+++ b/.github/workflows/regression-report.yml
@@ -13,11 +13,11 @@
 #####################################################################################
 name: regression-report
 env:
-  AWS_REGION: us-east-2
-  AWS_BUCKET_NAME: "checkstyle-diff-reports"
+  AWS_REGION: ap-south-1
+  AWS_BUCKET_NAME: "chesktyler-reports"
   USER_LOGIN: ${{ github.event.issue.user.login }}
   # yamllint disable-line rule:line-length
-  DEFAULT_PROJECTS_LINK: "https://raw.githubusercontent.com/checkstyle/test-configs/main/extractor/src/main/resources/list-of-projects.properties"
+  DEFAULT_PROJECTS_LINK: "https://raw.githubusercontent.com/checkstyle/test-configs/main/extractor/src/main/resources/list-of-projects.yml"
   BASE_TEST_CONFIGS_URL: "https://raw.githubusercontent.com/checkstyle/test-configs/main"
   EXTRACTOR_VERSION: 2024-08-27
   DIFF_TOOL_VERSION: "1.0-SNAPSHOT-all"
@@ -200,7 +200,7 @@ jobs:
           BASE_URL="${{ env.BASE_TEST_CONFIGS_URL }}"
           CONFIG_BUNDLE="${{ needs.parse_comment.outputs.config_bundle }}"
           CONFIG_LINK="$BASE_URL/$CONFIG_BUNDLE/config.xml"
-          PROJECTS_LINK="$BASE_URL/$CONFIG_BUNDLE/list-of-projects.properties"
+          PROJECTS_LINK="$BASE_URL/$CONFIG_BUNDLE/list-of-projects.yml"
           ./.ci/append-to-github-output.sh "config_link" "$CONFIG_LINK"
           ./.ci/append-to-github-output.sh "projects_link" "$PROJECTS_LINK"
 
@@ -249,7 +249,7 @@ jobs:
       - name: Download Extractor JAR
         uses: robinraju/release-downloader@v1.8
         with:
-          repository: "checkstyle/test-configs"
+          repository: "relentless-pursuit/test-configs"
           tag: "extractor-${{env.EXTRACTOR_VERSION}}"
           fileName: "extractor-all-${{env.EXTRACTOR_VERSION}}.jar"
 
@@ -274,8 +274,8 @@ jobs:
           CONFIG_FILE_NAME=$(basename "$FOUND_FILE" .java)_config.xml
           CONFIG_FILE_PATH="$OUTPUT_DIR/$CONFIG_FILE_NAME"
 
-          # Generate a name for the projects file
-          PROJECT_FILE_PATH="$OUTPUT_DIR/projects.properties"
+          # Generate a name for the projects YAML file
+          PROJECT_FILE_PATH="$OUTPUT_DIR/projects.yml"
 
           # Run the extractor
           java -jar extractor-all-${{env.EXTRACTOR_VERSION}}.jar \
@@ -291,6 +291,7 @@ jobs:
           # Print the contents of the files to the logs
           echo "Contents of CONFIG_FILE_PATH:"
           cat "$CONFIG_FILE_PATH"
+
 
       - name: Cache Generated Config and Project Files
         uses: actions/cache@v4
@@ -330,6 +331,7 @@ jobs:
           PULL_REQUEST_URL: ${{ github.event.issue.pull_request.url }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          git log -1
           mkdir -p .ci-temp
           # convert windows line endings to unix in event text
           echo "$ISSUE_BODY" > .ci-temp/windows.txt
@@ -362,12 +364,10 @@ jobs:
           || ''
         }}
     steps:
-      - name: Restore cache
-        uses: actions/cache/restore@v4
+      - name: Checkout master branch
+        uses: actions/checkout@v4
         with:
           path: .
-          key: ${{ env.CACHE_KEY }}
-          fail-on-cache-miss: true
 
       - name: Restore Generated Config and Project Files
         if: needs.handle_generated_config_bundle.result == 'success'
@@ -386,7 +386,7 @@ jobs:
           echo "Config link: $DIFF_CONFIG_LINK"
           echo "Projects link: $DIFF_PROJECTS_LINK"
           cp "$DIFF_CONFIG_LINK" .ci-temp/diff_config.xml
-          cp "$DIFF_PROJECTS_LINK" .ci-temp/project.properties
+          cp "$DIFF_PROJECTS_LINK" .ci-temp/projects.yml
 
       - name: Download URL-based Config and Project File
         id: download_files
@@ -412,18 +412,21 @@ jobs:
             }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          mkdir -p .ci-temp
+          git log -1
           if ! ./.ci/diff-report.sh download-files; then
             ./.ci/append-to-github-output.sh "failed" "true"
             exit 1
           fi
+
+      - name: List .ci-temp directory
+        run: ls -la .ci-temp
 
       - name: Cache config files
         uses: actions/cache@v4
         with:
           path: |
             .ci-temp/*.xml
-            .ci-temp/project.properties
+            .ci-temp/projects.yml
           key: ${{ env.CACHE_KEY }}-config-files
 
   make_report:
@@ -445,7 +448,7 @@ jobs:
         with:
           path: |
             .ci-temp/*.xml
-            .ci-temp/project.properties
+            .ci-temp/projects.yml
           key: ${{ env.CACHE_KEY }}-config-files
 
       - name: Restore local maven cache
@@ -457,7 +460,7 @@ jobs:
       - name: Download DiffTool JAR
         uses: robinraju/release-downloader@v1.8
         with:
-          repository: "checkstyle/test-configs"
+          repository: "relentless-pursuit/test-configs"
           tag: "diff-java-tool-${{ env.DIFF_TOOL_VERSION }}"
           fileName: "diff-java-tool-${{ env.DIFF_TOOL_VERSION }}.jar"
           out-file-path: ".ci-temp"
@@ -495,16 +498,21 @@ jobs:
           fi
           echo "-------------------------"
 
-      - name: Print project.properties
+      - name: Print projects file
         run: |
-          echo "Contents of project.properties:"
-          echo "-------------------------------"
-          if [ -f .ci-temp/project.properties ]; then
-            cat .ci-temp/project.properties
+          if [ -f .ci-temp/projects.yml ]; then
+            echo "Contents of projects.yml:"
+            echo "-------------------------------"
+            cat .ci-temp/projects.yml
+            echo "-------------------------------"
+          elif [ -f .ci-temp/projects.properties ]; then
+            echo "Contents of projects.properties:"
+            echo "-------------------------------"
+            cat .ci-temp/projects.properties
+            echo "-------------------------------"
           else
-            echo "project.properties not found"
+            echo "No projects file found"
           fi
-          echo "-------------------------------"
 
       - name: Print patch_config.xml
         run: |
@@ -541,29 +549,37 @@ jobs:
           DIFF_CONFIG="${{ github.workspace }}/.ci-temp/diff_config.xml"
           PATCH_CONFIG="${{ github.workspace }}/.ci-temp/patch_config.xml"
           NEW_MODULE_CONFIG="${{ github.workspace }}/.ci-temp/new_module_config.xml"
-          PROJECT_PROPERTIES="${{ github.workspace }}/.ci-temp/project.properties"
+
+          # Determine the projects file path
+          if [ -f "${{ github.workspace }}/.ci-temp/projects.yml" ]; then
+            PROJECTS_FILE="${{ github.workspace }}/.ci-temp/projects.yml"
+          elif [ -f "${{ github.workspace }}/.ci-temp/projects.properties" ]; then
+            PROJECTS_FILE="${{ github.workspace }}/.ci-temp/projects.properties"
+          else
+            echo "Error: Projects file not found."
+            exit 1
+          fi
 
           # Paths to the JAR files
           DIFFTOOL_JAR="diff-java-tool-${{ env.DIFF_TOOL_VERSION }}.jar"
-          PATCH_DIFF_TOOL_JAR="patch-diff-report-tool-\
-          ${{ env.PATCH_DIFF_TOOL_VERSION }}-jar-with-dependencies.jar"
+          PATCH_DIFF_TOOL_JAR="patch-diff-report-tool-${{ env.PATCH_DIFF_TOOL_VERSION }}-jar-with-dependencies.jar"
 
           # Run DiffTool with appropriate arguments
           if [ -f "$NEW_MODULE_CONFIG" ]; then
             echo "Generating report for new module"
             java -jar "$DIFFTOOL_JAR" -r "$REPO" -p "$PR_BRANCH" -pc "$NEW_MODULE_CONFIG" \
-              -m single -l "$PROJECT_PROPERTIES" -xm "-Dcheckstyle.failsOnError=false" \
+              -m single -l "$PROJECTS_FILE" -xm "-Dcheckstyle.failsOnError=false" \
               --allowExcludes --diffToolJarPath "$PATCH_DIFF_TOOL_JAR"
           elif [ -f "$PATCH_CONFIG" ]; then
             echo "Generating report with patch config"
             java -jar "$DIFFTOOL_JAR" -r "$REPO" -b "$BASE_BRANCH" \
               -p "$PR_BRANCH" -bc "$DIFF_CONFIG" \
-              -pc "$PATCH_CONFIG" -l "$PROJECT_PROPERTIES" -xm "-Dcheckstyle.failsOnError=false" \
+              -pc "$PATCH_CONFIG" -l "$PROJECTS_FILE" -xm "-Dcheckstyle.failsOnError=false" \
               --allowExcludes --diffToolJarPath "$PATCH_DIFF_TOOL_JAR"
           else
             echo "Generating standard diff report"
             java -jar "$DIFFTOOL_JAR" -r "$REPO" -b "$BASE_BRANCH" -p "$PR_BRANCH" \
-              -c "$DIFF_CONFIG" -l "$PROJECT_PROPERTIES" -xm "-Dcheckstyle.failsOnError=false" \
+              -c "$DIFF_CONFIG" -l "$PROJECTS_FILE" -xm "-Dcheckstyle.failsOnError=false" \
               --allowExcludes --diffToolJarPath "$PATCH_DIFF_TOOL_JAR"
           fi
 
